Add server pub file definitions
Cirras/eo-protocol pull request #11
Opened 2023-12-28 14:50 UTC by sorokya

2024-01-01 08:30 UTC, ethanmoffat approved these changes
LGTM 👍

2024-01-05 12:11 UTC, Cirras requested changes

2024-01-05 12:11 UTC, cirras commented on xml/pub/server/protocol.xml
> +    <struct name="DropNpcDropRecord">
`NpcDrop` is fairly correct, but repetitive due to the `Drop` prefix.

How about `DropItemRecord`, or even collapsing it all the way down to `DropRecord`?

2024-01-05 12:11 UTC, cirras commented on xml/pub/server/protocol.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Let's have a `<comment>` on every meaningful top-level type.

2024-01-05 12:11 UTC, cirras commented on xml/pub/server/protocol.xml
> +        <field name="alt_spawn_enabled" type="bool:char"/>
"alt" -> "alternate"

2024-01-05 12:11 UTC, cirras commented on xml/pub/server/protocol.xml
> +        <field name="question1" type="string" length="question1_length"/>
This could be a fixed-size array of the following struct called `questions`:
```xml
<struct name="InnQuestionRecord">
    <length name="question_length" type="char"/>
    <field name="question" type="string" length="question_length"/>
    <length name="answer_length" type="char"/>
    <field name="answer" type="string" length="answer_length"/>
</struct>
```

2024-01-05 12:11 UTC, cirras commented on xml/pub/server/protocol.xml
> +        <field name="skill_id_requirement1" type="short"/>
This could be a fixed-size array of `short` called `skill_requirements`.

2024-01-05 12:11 UTC, cirras commented on xml/pub/server/protocol.xml
> +        <length name="total_skills_count" type="short"/>
`skills_count`

2024-01-05 12:11 UTC, cirras commented on xml/pub/server/protocol.xml
> +        <length name="total_drops_count" type="short"/>
`drops_count`

2024-01-05 12:11 UTC, cirras commented on xml/pub/server/protocol.xml
> +        <length name="total_trades_count" type="short"/>
`trades_count`

2024-01-05 12:11 UTC, cirras commented on xml/pub/server/protocol.xml
> +        <length name="total_crafts_count" type="char"/>
`crafts_count`

2024-01-05 12:11 UTC, cirras commented on xml/pub/server/protocol.xml
> +        <length name="total_messages_count" type="char"/>
`messages_count`

2024-01-05 12:11 UTC, cirras commented on xml/pub/server/protocol.xml
> +        <array name="npcs" type="TalkRecord"/>
I feel weird about the name `npcs` but also don't have any bright ideas for a better one.
(cc: @ethanmoffat)

2024-01-05 12:11 UTC, cirras commented on xml/pub/server/protocol.xml
> +        <field name="ingredient1_id" type="short"/>
This can be a fixed-size array of `ShopCraftIngredientRecord`.
```xml
<struct name="ShopCraftIngredientRecord">
    <field name="id" type="short"/>
    <field name="amount" type="char"/>
</struct>
```

2024-01-05 13:13 UTC, sorokya commented on xml/pub/server/protocol.xml
> +    <struct name="DropNpcDropRecord">
Went with `DropRecord`

2024-01-05 14:21 UTC, cirras requested changes

2024-01-05 14:21 UTC, cirras commented on xml/pub/server/protocol.xml
> +          <comment>Behavior ID of the NPC that runs the inn. 0 for default inn</comment>
Use 4 spaces for indentation.

2024-01-05 14:21 UTC, cirras commented on xml/pub/server/protocol.xml
> +          <comment>Map ID of the map the player is sent to after respawning</comment>
"ID of the map..."

2024-01-05 14:21 UTC, cirras commented on xml/pub/server/protocol.xml
> +          <comment>Map ID of the map the player is sent to after sleeping at the inn</comment>
"ID of the map..."

2024-01-05 14:21 UTC, cirras commented on xml/pub/server/protocol.xml
> +            Used in the original server so that default characters would respawn on noob island
"In the official server, this is used to respawn new characters on the noob island..."

2024-01-05 14:21 UTC, cirras commented on xml/pub/server/protocol.xml
> +            until they reached level 1.
Are you sure it's level 1?
I'm not.

2024-01-05 14:21 UTC, cirras commented on xml/pub/server/protocol.xml
> +        <array name="ingredients" type="ShopCraftIngredientRecord" length="4" />
formatting: remove space before the `/`

2024-01-05 14:21 UTC, cirras commented on xml/pub/server/protocol.xml
> +          <comment>
"Item ID of the craft ingredient, or 0 if the ingredient is not present"

2024-01-05 14:21 UTC, cirras commented on xml/pub/server/protocol.xml
> +          <comment>Array of skill IDs that must be learned before the player can learn this skill</comment>
"IDs of skills that must be learned before a player can learn this skill"

2024-01-05 14:21 UTC, cirras commented on xml/pub/server/protocol.xml
> +          How much it cost to buy the item from the shop
Missing surrounding `<comment>` element

2024-01-05 14:21 UTC, cirras commented on xml/pub/server/protocol.xml
> +          Max amount of the item that can be bought or sold at one time
Missing surrounding `<comment>` element

2024-01-05 14:21 UTC, Cirras commented on xml/pub/server/protocol.xml
> +          How much it cost to buy the item from the shop
"cost" -> "costs"

2024-01-05 14:21 UTC, Cirras commented on xml/pub/server/protocol.xml
> +          <comment>Chance 0-100 that a message will be sent<comment>
"Chance that the NPC will talk (0-100)"

2024-01-05 14:21 UTC, Cirras commented on xml/pub/server/protocol.xml
> +          <comment>ID of the NPC that will say these messages</comment>
"ID of the NPC that will talk"

2024-01-05 14:21 UTC, Cirras commented on xml/pub/server/protocol.xml
> +        <field name="alternate_spawn_enabled" type="bool:char">
The default [underlying type](https://github.com/Cirras/eo-protocol/blob/master/docs/types.md#underlying-types) of `bool` is already `char`.
`bool:char` can change to `bool`.

2024-01-05 14:45 UTC, sorokya commented on xml/pub/server/protocol.xml
> +            until they reached level 1.
I'm like 99% sure. You escaped with a scroll and then upon death respawn in the noob house. But it only worked if you were level 0

2024-01-05 15:02 UTC, Cirras requested changes
Great! Only a few minor pedantic comment tweaks remaining.

2024-01-05 15:02 UTC, Cirras commented on xml/pub/server/protocol.xml
> +        <comment>An NPC and the items it can drop when killed</comment>
"Record of potential drops from an NPC"

2024-01-05 15:02 UTC, Cirras commented on xml/pub/server/protocol.xml
> +        <comment>Record of a tradeable item in a shop</comment>
Record of an item that can be bought or sold in a shop

2024-01-05 15:02 UTC, Cirras commented on xml/pub/server/protocol.xml
> +        <comment>Record of an ingredient for a craftable item in a shop</comment>
Record of an ingredient for crafting an item in a shop

2024-01-05 15:02 UTC, Cirras commented on xml/pub/server/protocol.xml
> +        <comment>Record of a craftable item in a shop</comment>
Record of an item that can be crafted in a shop

2024-01-05 15:11 UTC, Cirras commented on xml/pub/server/protocol.xml
> +        <array name="npcs" type="TalkRecord"/>
On reflection, I actually think I'm okay with this.

2024-01-05 15:42 UTC, Cirras approved these changes
🚀

2024-01-05 15:43 UTC, merged