Change Effect_Player and Effect_Agree to send as array
Cirras/eo-protocol pull request #21
Opened 2024-03-20 18:40 UTC by sorokya

Noticed when testing weddings in GameServer. These are actually arrays and not single player/tile.

```
19:28:58.140 [S->C] Effect_Player
1B 3 2 FE FE 9B 3 2 FE FE

19:28:58.141 [S->C] Effect_Player
1B 3 2 FE FE 9B 3 2 FE FE

19:28:58.141 [S->C] Effect_Player
1B 3 2 FE FE 9B 3 2 FE FE

19:28:59.850 [S->C] Effect_Agree
9 9 C FE 9 A C FE

19:28:59.850 [S->C] Effect_Agree
9 9 C FE 9 A C FE
```

2024-03-26 11:51 UTC, Cirras requested changes
Nice find.
I have some thoughts on the struct/packet comments, otherwise looks good.

2024-03-26 11:51 UTC, Cirras commented on xml/net/server/protocol.xml
> +        <comment>List of players and effect to play for each</comment>
`Effects playing on nearby players`

2024-03-26 11:51 UTC, Cirras commented on xml/net/server/protocol.xml
> +        <comment>List of tiles and effect to play for each</comment>
`Effects playing on nearby tiles`

2024-03-26 11:51 UTC, Cirras commented on xml/net/server/protocol.xml
> +        <comment>A player doing an effect</comment>
`An effect playing on a player`

2024-03-26 12:07 UTC, Cirras commented
I've tested and confirmed the behavior in the official client.

2024-03-27 09:34 UTC, sorokya commented
@Cirras comments updated

2024-03-27 13:36 UTC, Cirras approved these changes
Looks good, thanks!

2024-03-27 13:37 UTC, merged