Change some NPC reply fields to optional and add documentation
Cirras/eo-protocol pull request #23
Opened 2024-04-14 09:30 UTC by sorokya

2024-04-20 11:05 UTC, Cirras requested changes
Thanks! Had a couple of questions.

2024-04-20 11:05 UTC, Cirras commented on xml/net/server/protocol.xml
> +        <comment>Nearby NPC killed and killer leveled up</comment>
So just to be clear, on EOS this packet is sent to all nearby players if the killer leveled up (minus optional fields)?

2024-04-20 11:05 UTC, Cirras commented on xml/net/server/protocol.xml
>          <comment>Nearby NPC killed by player spell and you leveled up</comment>
For consistency, should we be adjusting the wording here?
The packet works similarly to `NPC_ACCEPT` in that everyone in range receives it, but only the killer gets the optional fields (right?)
```suggestion
        <comment>Nearby NPC killed by player spell and killer leveled up</comment>
```

2024-04-30 10:24 UTC, sorokya commented on xml/net/server/protocol.xml
> +        <comment>Nearby NPC killed and killer leveled up</comment>
Yes

2024-04-30 15:10 UTC, Cirras approved these changes
Thanks!

2024-04-30 15:10 UTC, merged